#!/bin/bash
#

install_fedora_pkgs() {
  sudo dnf install -y htop tmux xfce4-terminal zsh
  sudo dnf groupinstall -y "Development Tools"
  # sudo dnf install direnv
}

install_ubuntu_pkgs() {
  sudo apt-get update
  sudo apt-get install -y vim vim-gtk3 direnv
}

IS_FEDORA=1
IS_UBUNTU=1

if [ -f /etc/os-release ]; then
  grep '^NAME=Fedora' /etc/os-release -q
  IS_FEDORA=$(($? == 0))


  if [ "$IS_FEDORA" -eq "0" ]; then
    grep '^ID_LIKE=.\?fedora' /etc/os-release -q
    IS_FEDORA=$(($? == 0))
  fi

  grep '^NAME=.\?Ubuntu' /etc/os-release -q
  IS_UBUNTU=$(($? == 0))
fi

if [ "$IS_FEDORA" -ne "0" ]; then
  install_fedora_pkgs
elif [ "$IS_UBUNTU" -ne "0" ]; then
  install_ubuntu_pkgs
fi

