#!/bin/env zsh

function app-install() {
  app=$1

  if [[ "minikube" = "$1" ]]; then
    $HOME/Projects/linux-workspace/shell-functions/app-install-helpers/install-minikube
  fi
  if [[ "ko" = "$1" ]]; then
    $HOME/Projects/linux-workspace/shell-functions/app-install-helpers/install-ko
  fi
  if [[ "kubectl" = "$1" ]]; then
    $HOME/Projects/linux-workspace/shell-functions/app-install-helpers/install-kubectl
  fi
  if [[ "kustomize" = "$1" ]]; then
    $HOME/Projects/linux-workspace/shell-functions/app-install-helpers/install-kustomize
  fi
  if [[ "crc" = "$1" ]]; then
    $HOME/Projects/linux-workspace/shell-functions/app-install-helpers/install-crc
  fi
}
