#!/bin/env zsh

function app-install() {
  helpers_directory=$HOME/Projects/linux-workspace/shell-functions/app-install-helpers
  helper_script=$helpers_directory/install-$1
  helper_script=${helper_script:A}

  if [[ "${helper_script:h}" != "${helpers_directory}" ]]; then
    echo "The string $1 is not a valid argument."
  elif [[ ! -f "$helper_script" ]]; then
    echo "There is no script to install $1"
  else
    $helper_script
  fi
}
